



# PHP Settings
php_version:  "8.1"
wp_version: "6.6.1"
php_modules: [ 'php8.1-curl', 'php8.1-gd', 'php8.1-mbstring', 'php8.1-xml', 'php8.1-xmlrpc', 'php8.1-soap', 'php8.1-intl', 'php8.1-zip' ]
#HTTP Settings
file_http_host:                                                                                                               
  - 'srv_web_directory_name'
http_host: 
  - 'domains'
http_port: "80"


sites:
  - {file_http_host: 'srv_web_directory_name', file_http_log: 'log_file_name', http_host: 'doamin' }


database:
  - {file_http_host: 'srv_web_directory_name', db_name: 'db_name', db_user: 'db_user', db_password: 'db_password', db_host: 'db_host' }
